##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/marco/trunk/PKGBUILD
    - autoconf-archive
    - clang
    - gcc
    - git
    - glib2
    - gtk3
    - intltool
    - libcanberra
    - libgtop
    - libxpresent
    - make
    - mate-common
    - mate-desktop
    - meson
    - which
    - yelp-tools
    - zenity

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/marco
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gcc
    - git
    - intltool
    - libcanberra-gtk3-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtop2-dev
    - libice-dev
    - libpango1.0-dev
    - libsm-dev
    - libstartup-notification0-dev
    - libx11-dev
    - libxcomposite-dev
    - libxcursor-dev
    - libxdamage-dev
    - libxext-dev
    - libxfixes-dev
    - libxinerama-dev
    - libxpresent-dev
    - libxrandr-dev
    - libxrender-dev
    - libxt-dev
    - make
    - mate-common
    - meson
    - x11proto-present-dev
    - yelp-tools
    - zenity

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/marco.git
    - autoconf-archive
    - clang-analyzer
    - clang
    - cppcheck-htmlreport
    - desktop-file-utils
    - gcc
    - git
    - gtk3-devel
    - libSM-devel
    - libXdamage-devel
    - libXpresent-devel
    - libcanberra-devel
    - libgtop2-devel
    - libsoup-devel
    - make
    - mate-common
    - mate-desktop-devel
    - meson
    - redhat-rpm-config
    - startup-notification-devel
    - yelp-tools
    - zenity

  ubuntu:
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - gcc
    - git
    - intltool
    - libcanberra-gtk3-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtop2-dev
    - libice-dev
    - libpango1.0-dev
    - libsm-dev
    - libstartup-notification0-dev
    - libx11-dev
    - libxcomposite-dev
    - libxcursor-dev
    - libxdamage-dev
    - libxext-dev
    - libxfixes-dev
    - libxinerama-dev
    - libxpresent-dev
    - libxrandr-dev
    - libxrender-dev
    - libxt-dev
    - make
    - mate-common
    - meson
    - x11proto-present-dev
    - yelp-tools
    - zenity

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:
  - cd ${START_DIR}
  - '[ -f mate-common-1.24.1.tar.xz ] || curl -Ls -o mate-common-1.24.1.tar.xz https://github.com/mate-desktop/mate-common/releases/download/v1.24.1/mate-common-1.24.1.tar.xz'
  - tar xf mate-common-1.24.1.tar.xz
  - cd mate-common-1.24.1
  - if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -     ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu
  - else
  -     ./configure --prefix=/usr
  - fi
  - make
  - make install

build_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     export CFLAGS+=" -Wsign-compare -Wunused-parameter"
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude --force -D'PACKAGE' -D'WITH_VERBOSE_MODE' .
  - fi

  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure --enable-compile-warnings=maximum
  - if [ $CPU_COUNT -gt 1 ]; then
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make -j $CPU_COUNT
  -         make clean
  -     fi
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make
  -         make clean
  -     fi
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi

after_scripts:
  - if [ ${DISTRO_NAME} == "fedora" ];then
  -   cppcheck --xml --output-file=cppcheck.xml --enable=warning,style,performance,portability,information,missingInclude --force -D'PACKAGE' -D'WITH_VERBOSE_MODE' .
  -   cppcheck-htmlreport --title=${REPO_NAME} --file=cppcheck.xml --report-dir=cppcheck-htmlreport
  -   ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/mate-icon-theme/raw/master/mate/16x16/apps/preferences-system-windows.png
  - fi
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: marco-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
