.\" Man page for marco-message.
.TH MARCO-MESSAGE 1 "8 February 2014" "MATE Desktop Environment"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH "NAME"
marco\-message \- A command to send messages to Marco.
.SH "SYNOPSIS"
.B marco\-message [OPTIONS]
.SH "DESCRIPTION"
The \fBmarco\-message\fP command is used to perform some simple window manager tasks while Marco is running.

.SH "OPTIONS"
.TP
\fBrestart\fR
Restart a currently running instance of \fBmarco\fP.
.TP
\fBreload\-theme\fR
Reload the current window border theme specified in the dconf database. (/org/mate/marco/general/theme)
.TP
\fBenable\-keybindings\fR
Enable all keybindings specified in the dconf database. (/org/mate/marco/)
.TP
\fBdisable\-keybindings\fR
Disable all keybindings specified in the dconf database. (/org/mate/marco/)
.TP
\fBtoggle\-verbose\fR
Enable or Disable debugging messages for \fBmarco\fR.

.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
http://github.com/mate-desktop/marco/issues
.SH "AUTHORS"
.SS This Man Page has been updated/re-written for the MATE Desktop Environment by:
Adam Erdman <hekel@archlinux.info> (2014)
.SH "HISTORY"
.SS Portions of this manpage were originally written for the Debian GNU/Linux system by:
Akira TAGOH <tagoh@debian.org> (2002)
.SH "SEE ALSO"
.SS Further information may also be available at: http://wiki.mate-desktop.org/docs
.P
.BR marco (1),
.BR marco-theme-viewer (1),
.BR marco-window-demo (1)
