.\" Man page for marco-message.
.TH MARCO-WINDOW-DEMO 1 "9 February 2014" "MATE Desktop Environment"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH "NAME"
marco-window-demo \- demo of window features
.SH "SYNOPSIS"
.B marco-window-demo
.SH "DESCRIPTION"
This program demonstrates various kinds of windows that window managers and window manager themes should handle.
.PP
Be sure to tear off the menu and toolbar, those are also a special
kind of window.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
http://github.com/mate-desktop/marco/issues
.SH "AUTHORS"
.SS This Manual page was originally written for the Debian GNU/Linux system by: 
Jose M. Moya <josem@die.upm.es> (2004)
.SS It has been updated for the MATE Desktop Environment by:
Adam Erdman <hekel@archlinux.info> (2014)
.SH "SEE ALSO"
.SS Further information may also be available at: http://wiki.mate-desktop.org/docs
.P
.BR xorg (1),
.BR marco (1),
.BR marco-message (1),
.BR marco-theme-viewer (1).
